apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: zipkin-srv
  labels:
    app: zipkin-srv
spec:
  type: LoadBalancer
  ports:
  - port: 9411
    name: zipkin
    targetPort: 9411
    nodePort: 31003
  selector:
    app: zipkin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411
