apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello2-srv
  labels:
    app: hello2-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: hello2
    targetPort: 8080
    nodePort: 31006
  selector:
    app: hello2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
      - name: hello2
        image: amitrepo/hello2java:0.0.1
        ports:
        - containerPort: 8080
