apiVersion: v1
kind: Secret
metadata:
  name: consul-token
type: Opaque 
data:
  consul-token: YWJjNjlkZTEtOWVhZi00NjViLWJiNmMtMWQzMTdjNGRhZjlh
  #Token create by this command #echo -n 'abc69de1-9eaf-465b-bb6c-1d317c4daf9a' | base64