apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: college-srv
  labels:
    app: college-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    name: college
    targetPort: 8082
    nodePort: 31005
  selector:
    app: college
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: college
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: college
    spec:
      containers:
      - name: college
        image: amitrepo/envconsul-java-app-college:0.0.2
        ports:
        - containerPort: 8082
