---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: consul
  labels:
    app: consul
spec:
  type: LoadBalancer
  ports:
  - port: 8500
    name: consul
    targetPort: 8500
    nodePort: 30001
  selector:
    app: consul

---

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: consul
spec:
  serviceName: consul
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:1.0.2
        ports:
        ports:
          - containerPort: 8300
            name: server
          - containerPort: 8301
            name: serflan-tcp
            protocol: "TCP"
          - containerPort: 8301
            name: serflan-udp
            protocol: "UDP"
          - containerPort: 8302
            name: serfwan-tcp
            protocol: "TCP"
          - containerPort: 8302
            name: serfwan-udp
            protocol: "UDP"
          - containerPort: 8400
            name: rpc-port
          - containerPort: 8500
            name: api-port
          - containerPort: 8600
            name: consuldns-tcp
            protocol: "TCP"
          - containerPort: 8600
            name: consuldns-udp
            protocol: "UDP"
