apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: consul2
  labels:
    app: consul2
spec:
  type: LoadBalancer
  ports:
  - port: 8500
    name: consul2
    targetPort: 8500
    nodePort: 30002
  selector:
    app: consul2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consul2
    spec:
      containers:
      - name: consul2
        image: consul:1.0.2
        ports:
          - containerPort: 8300
            name: server
          - containerPort: 8301
            name: serflan-tcp
            protocol: "TCP"
          - containerPort: 8301
            name: serflan-udp
            protocol: "UDP"
          - containerPort: 8302
            name: serfwan-tcp
            protocol: "TCP"
          - containerPort: 8302
            name: serfwan-udp
            protocol: "UDP"
          - containerPort: 8400
            name: rpc-port
          - containerPort: 8500
            name: api-port
          - containerPort: 8600
            name: consuldns-tcp
            protocol: "TCP"
          - containerPort: 8600
            name: consuldns-udp
            protocol: "UDP"
