apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello-srv
  labels:
    app: hello-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    name: hello
    targetPort: 8081
    nodePort: 31005
  selector:
    app: hello
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: amitrepo/hellojava:0.0.1
        ports:
        - containerPort: 8081
