apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: git2consul-dev
spec:
  selector:
    matchLabels:
      app: git2consul-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: git2consul-dev
    spec:
      containers:
      - name: git2consul-dev
        image: amitrepo/git2consul:0.12.13
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CONSUL_ENDPOINT
#          value: 172.30.106.215
          value: consul.glt-consul.svc.cluster.local
        - name: CONSUL_PORT
          value: "8500"
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: consul-token
              key: consul-token
#        - name: CONFIG_KEY
#          value: glt-uat/git2consul/config
        volumeMounts:
          - name: config
            mountPath: /etc/git2consul.d/
      volumes:
          - name: config
            configMap:
              name: git2consul-dev