apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: app2-srv
  labels:
    app: app2-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    name: app2
    targetPort: 8000
    nodePort: 31005
  selector:
    app: app2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: amitrepo/envconsul-java-app-app2:0.0.2
        ports:
        - containerPort: 8000
