---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nginx2
  labels:
    app: nginx2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: nginx2
    targetPort: 80
    nodePort: 31002
  selector:
    app: nginx2

---

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: nginx2
spec:
  serviceName: nginx2
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx
        ports:
        - containerPort: 80
